### PR TITLE
Make the GUI initialization more robust.

### PR DESCRIPTION
**Pull request by Adelrisk**
I was very concerned that my code broke, and that the fix involved calling some methods in a different order.

I've fixed that, making the code more robust.

### CODE REVIEW

**Comment by sake** [comment]
The prepare function must be called in the onStartCommand function as the promise must be cleared each time an activation request is made.

**Comment by Adelrisk** [comment]
I'd like to record my decision to remove the call `prepare()` from `onStartCommand` in `EacGuiService.java`.

https://developer.android.com/reference/android/app/Service.html 

> If someone calls Context.startService() then the system will retrieve the service (creating it and calling its onCreate() method if needed) and then call its onStartCommand(Intent, int, int) method with the arguments supplied by the client. [...] Note that multiple calls to Context.startService() do not nest (though they do **result in multiple corresponding calls to onStartCommand()**)

 (emphasis mine)

Basically, if a client has started the service and waits on it (due to the blocking in `onBind`) and another client starts the service and thus calls `prepare()`, then the first client ends up waiting on a promise that will never be delivered or cancelled.

**Comment by sake** [comment]
The actual question is when the future should be refreshed. During the initial implementation this has been changed a few times and after thinking about again I believe this should be done in the activity starting handling the activation (AbstractActivationActivity) as this is the first thing someone who wants to use the app is doing. So startService is called once for a process. I suppose we should do initialization in the activity and destroy the promise in the activity when the activity is finished (redirect back to caller). This should also make it obsolete to call the function when the UI closes.

As the App can only handle one process at a time, it should prevent further activations until the current one is finished.

**Comment by Adelrisk** [comment]
> The actual question is when the future should be refreshed.

That is a discussion that extends the scope of the current changes, which are about hardening `EacGuiService` so that clients won't break. (Solved, btw, see the tests.) A side effect involves changing the offered methods and their behaviour on `EacGuiService`.

Can these changes be used to implement your described behaviour? Or are you asking me if it can be done?

**Pull request merged**
